// Note: the capability of this was converted from https://css.glass/

export default function generateGlassmorphismCSS({transparency, color, blur, outline}) {
    const outlineCSS = outline
        ? `\nborder: 1px solid rgba(${color.r}, ${color.g}, ${color.b}, ${outline});`
        : '';

    return `
    /* Begin autogenerated */
    background: rgba(${color.r}, ${color.g}, ${color.b}, ${transparency});
    border-radius: 16px;
    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
    backdrop-filter: blur(${blur}px);
    -webkit-backdrop-filter: blur(${blur}px);${outlineCSS}   
    /* End autogenerated */
  `.trim(); // Trim to remove extra whitespace
}



